#+ summary: Query to get 10 subjects from the KB that match some text (with a regex)
#+ endpoint: http://data.bibliotheken.nl/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?subjectId ?subjectName where 
{?Concept <http://schema.org/about> ?subjectId . ?subjectId skos:prefLabel ?subjectName filter regex(str(?subjectName), ?_text, "i")} LIMIT 10 