#+ summary: Query to get all persons associated with a person (at present only via creator relations)
#+ endpoint: http://zorin.beeldengeluid.nl:3020/sparql/

PREFIX schema: <http://data.rdlabs.beeldengeluid.nl/schema/>

SELECT DISTINCT ?personName 
WHERE {
?s a schema:Program . ?s schema:creator ?personId . ?personId schema:name ?_name . ?s schema:creator ?colleagueId . ?colleagueId schema:name ?personName FILTER(?personName != ?_name)
}
