#+ summary: Query to get all persons associated with a person
#+ endpoint: http://zorin.beeldengeluid.nl:3020/sparql/
PREFIX nisv: <http://data.rdlabs.beeldengeluid.nl/schema/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?personName 
WHERE {
?s a nisv:Program . ?s ?personProperty ?personInRoleId . ?personInRoleId nisv:hasPerson ?personId  . ?s ?personProperty ?colleagueId . ?colleagueId nisv:hasPerson ?person2Id . ?person2Id skos:prefLabel ?personName FILTER(?personName != ?personId ?_name_nl). ?personId ?_name_nl . ?personProperty rdfs:subPropertyOf nisv:hasEntityInRole

}

