#+ summary: Query to get all persons associated with a program (at present only creators)
#+ endpoint: http://zorin.beeldengeluid.nl:3020/sparql/
PREFIX nisv: <http://data.rdlabs.beeldengeluid.nl/schema/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?person ?personName WHERE
{
?_o1_iri nisv:hasCreator ?creator . ?creator nisv:hasPerson ?person . ?person skos:prefLabel ?personName
}
ORDER BY ?personName
