#+ summary: Query to get all subjects associated with a program
#+ endpoint: http://zorin.beeldengeluid.nl:3020/sparql/

PREFIX nisv: <http://data.rdlabs.beeldengeluid.nl/schema/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?keyword WHERE
{
?_o1_iri nisv:hasKeyword ?keyword
}
ORDER BY ?keyword
