#+ summary: Test query, gets 10 items with the given type
#+ endpoint: http://zorin.beeldengeluid.nl:3020/sparql/
#+ defaults:
#+  - lim: 10

PREFIX schema: <http://data.rdlabs.beeldengeluid.nl/schema/>
SELECT ?s WHERE {?s a ?_o1} LIMIT 10