PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX sdo: <https://schema.org/>
SELECT ?z ?pref_label ?t
WHERE {
	VALUES ?s { <http://data.beeldengeluid.nl/id/program/2102501280372631431> } . 
	?s ((sdo:creator/sdo:creator)|(sdo:byArtist/sdo:byArtist)|(sdo:actor/sdo:actor)|(sdo:contributor/sdo:contributor|(sdo:productionCompany/sdo:productionCompany))) ?z . 
	?z skosxl:prefLabel/skosxl:literalForm ?pref_label .
	?z sdo:additionalType ?t
	}
