PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sdo: <https://schema.org/>
SELECT ?z ?label ?t
WHERE {
	VALUES ?s { <http://data.beeldengeluid.nl/id/program/2102501280372631431> } . 
	?s (sdo:creator|sdo:byArtist|sdo:actor|sdo:contributor|sdo:productionCompany)/sdo:roleName ?z . 
	?z rdfs:label ?label . 
  ?z rdf:type ?t 
}