class DataCatalogLODHandler:
    """ Handles requests from the beng-lod server for data catalogs, datasets, datadownloads.
        The source for the data catalog is a (Turtle) file in /resource. If the dile doesn't exist,
        it is generated by the utility class /src/util/DatasetSheetImporter. This class reads data
        from a Google spreadsheet, that is the source of all data.
    """
    def __init__(self):
        pass

