on:
  workflow_call:

name: Deploy to Amazon ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get lowercase repo name
      id: repoName
      run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')"
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

    - name: Build, tag, and push image to private Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ steps.repoName.outputs.reponame }}:${{ steps.sha.outputs.sha7 }} -t $ECR_REGISTRY/${{ steps.repoName.outputs.reponame }}:latest .
        docker push $ECR_REGISTRY/${{ steps.repoName.outputs.reponame }} --all-tags
