name: Build & Push

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@bede4a84f512e0b39c9f063b42ef786a8c305dab # v2026.07.09
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
