name: Build & Push

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@4582943626e94afc4c41f08651f1523150791f33 # v2026.08.20
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
