name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@7e2a13e12af5ae6e9c431f541297f8d8d37c073e # v2026.09.25
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
