name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@06e8f266836216a02b84dec2fb8a21b78c56b356 # v2026.08.05
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
