name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@ec3fa53a64d7cb6be5a435cd11827af7394ee55f # v2026.04.17
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
