name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev --three
    - name: Test with pytest
      run: |
        pipenv install pytest pytest-cov --dev
        pipenv run pytest src/tests/unit_tests
    - name: Lint with flake8
      run: |
        pipenv install flake8
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  deploy:

    runs-on: self-hosted
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: install with puppet
      run: |
        cd /etc/puppetlabs/code/modules/rd_infra_service/
        sudo puppet apply examples/test-cluster/beng_lod_server.pp
