name: Main branch

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    uses: ./.github/workflows/test.yml

  push-to-registry:
    # if: ${{ false }} # until aws-ecr push works
    uses: ./.github/workflows/aws-ecr.yml
    secrets: inherit

  deploy-acc:
    uses: ./.github/workflows/deploy.yml
    needs: [test]
    with:
      target: acc
