name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        options:
        - "acc"
        - "prd"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ inputs.target }}
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      target: "acc"
