name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      selected_target:
        type: choice
        required: true
        options:
        - "acc"
        - "prd"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ github.events.inputs.selected_target }}
