name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        options:
        - "acc"
        - "prd"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ format('{0}', inputs.target) }}
