name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      selected_target:
        type: choice
        required: true
        default: prd
        options:
        - acc
        - prd

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ github.event.inputs.selected_target }}
