on:
  push:
    branches:
      - "master"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy-acc:
    uses: ./.github/workflows/deploy.yml
    needs: [test]
    with:
      target: acc
