on:
  push:
    branches:
      - "master"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: [self-hosted]
    needs: test
    steps:
    - name: Update ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        sudo git pull
    - name: autodeploy to acc with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook beng-lod-server.yml --extra-vars "env=acc app_version=master"

  deploy_aws:
    runs-on: [self-hosted, aws]
    needs: [test]
    steps:
    - name: Update ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        sudo git pull
    - name: autodeploy to aws with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook beng-lod-server.yml  --extra-vars "env=odl app_version=master app_port=80"
