name: Master branch

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    uses: ./.github/workflows/test.yml

jobs:
  push-to-registry:
    uses: ./.github/workflows/aws-ecr.yml
    secrets: inherit

  deploy-acc:
    uses: ./.github/workflows/deploy.yml
    needs: [test]
    with:
      target: acc
