name: Test, lint and deploy Master branch

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv with command
      run: pip install pipenv
    - name: Install dependencies (including dev-packages)
      run: pipenv install --three --dev --skip-lock
    - name: Test with pytest
      run: pipenv run pytest src/tests
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  deploy:
    runs-on: [self-hosted, lechiffre]
    needs: test
    steps:
    # - name: Update ansible
      # run: |
       #  cd /opt/git/x-omgeving/ansible/
       #  sudo git pull
    - name: autodeploy to acc with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook beng-lod-server.yml --extra-vars "env=acc app_version=master"

  deploy_aws:
    runs-on: [self-hosted, aws]
    needs: [test]
    steps:
    - name: autodeploy to aws with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook beng-lod-server.yml  --extra-vars "env=odl app_version=master app_port=80"
